version: '3.8'

services:
  llm:
    platform: ${LLM_PLATFORM}
    build:
      context: ./llm
      dockerfile: Dockerfile
    command: >
      -m /models/${LLM_MODEL} --host 0.0.0.0 --port ${LLM_PORT}
      -t ${LLM_THREADS} -c ${LLM_CTX} --n-predict ${LLM_N_PREDICT} --chat-template mistral
    volumes:
      - ${LLM_MODELS_DIR}:/models:ro
      # - ./llm/ui:/ui:ro 
    ports:
      - "${LLM_PORT}:${LLM_PORT}"
    restart: unless-stopped
    env_file:
      - ./.env.llm
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${LLM_PORT}/v1/models"]
      interval: 10s
      timeout: 5s
      retries: 8


  web:
    build:
      context: ./django_app
      dockerfile: Dockerfile.prod
    restart: always  
    command: sh -c "python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        exec gunicorn django_app.wsgi:application
        --bind 0.0.0.0:8000
        --workers 2
        --threads 4
        --worker-class gthread
        --timeout 600
        --graceful-timeout 600
        --keep-alive 75"
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      pg_db:
        condition: service_healthy
      llm:
        condition: service_healthy
    environment:
          - LLM_SERVER_URL=http://llm:${LLM_PORT}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://web:8000/health"]
      interval: 15s
      timeout: 3s
      retries: 5


  pg_db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 3s
      retries: 5


  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    restart: always
    ports:
      - "200:80"
      - "81:81"   # NPM UI access
      - "443:443"
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
  # nginx-proxy:
  #   container_name: nginx-proxy
  #   build: nginx
  #   restart: always
  #   ports:
  #     - 443:443
  #     - 200:80
  #   volumes:
  #     - static_volume:/home/app/web/staticfiles
  #     - media_volume:/home/app/web/mediafiles
  #     - certs:/etc/nginx/certs
  #     - html:/usr/share/nginx/html
  #     - vhost:/etc/nginx/vhost.d
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #   depends_on:
  #     - web

  # acme-companion:
  #   image: nginxproxy/acme-companion
  #   restart: always
  #   env_file:
  #     - ./.env.prod.proxy-companion
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - certs:/etc/nginx/certs
  #     - html:/usr/share/nginx/html
  #     - vhost:/etc/nginx/vhost.d
  #     - acme:/etc/acme.sh
  #   depends_on:
  #     - nginx-proxy

  nextcloud_db:
    image: mariadb:10.11
    container_name: nextcloud_db
    restart: unless-stopped
    env_file:
      - ./.env.prod.nextcloud
    volumes:
      - /mnt/nextcloud_data/data:/var/lib/mysql

  nextcloud_redis:
    image: redis:7
    container_name: nextcloud_redis
    restart: unless-stopped

  nextcloud_app:
    image: nextcloud
    container_name: nextcloud_app
    restart: unless-stopped
    environment:
      - PHP_UPLOAD_MAX_FILESIZE=10G
      - PHP_POST_MAX_SIZE=10G
    env_file:
      - ./.env.prod.redis
    volumes:
      - /mnt/nextcloud_data/app:/var/www/html
    networks:
      - default
    depends_on:
      - nextcloud_db
      - nextcloud_redis

  # telegram_bot:
  #   build: ./telegram_bot
  #   restart: always
  #   depends_on:
  #     - web
  #   env_file:
  #     - ./.env.prod

  # pihole:
  #   image: pihole/pihole
  #   container_name: pihole
  #   ports:
  #     - "53:53/tcp"
  #     - "53:53/udp"
  #     - "100:80/tcp"
  #   environment:
  #     - TZ=Asia/Kolkata
  #     - WEBPASSWORD=${PIHOLE_WEBPASSWORD}
  #     - ServerIP=192.168.0.200
  #   volumes:
  #     - pihole_etc_pihole:/etc/pihole
  #     - pihole_etc_dnsmasq:/etc/dnsmasq.d
  #   restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
  acme:
  npm_data:
  npm_letsencrypt:
  # pihole_etc_pihole:
  # pihole_etc_dnsmasq:
