# Generated by Django 4.2.3 on 2023-12-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('open', models.IntegerField(default=0)),
                ('high', models.IntegerField(default=0)),
                ('low', models.IntegerField(default=0)),
                ('close', models.IntegerField(default=0)),
            ],
        ),
    ]
