# Generated by Django 4.2.3 on 2023-12-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo_trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldata',
            name='close',
            field=models.DecimalField(decimal_places=5, max_digits=7),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='high',
            field=models.DecimalField(decimal_places=5, max_digits=7),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='low',
            field=models.DecimalField(decimal_places=5, max_digits=7),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='open',
            field=models.DecimalField(decimal_places=5, max_digits=7),
        ),
    ]
