# Generated by Django 4.2.3 on 2024-09-10 14:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('algo_trading', '0002_alter_historicaldata_close_alter_historicaldata_high_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldata',
            name='id',
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='ticker',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
