# Generated by Django 4.2.3 on 2024-09-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo_trading', '0003_remove_historicaldata_id_historicaldata_ticker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaldata',
            name='total_traded_quantity',
            field=models.BigIntegerField(default=0),
        ),
    ]
