# Generated by Django 4.2.3 on 2024-09-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo_trading', '0004_historicaldata_total_traded_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldata',
            name='close',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='high',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='low',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='open',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
