# Generated by Django 4.2.3 on 2024-09-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo_trading', '0005_alter_historicaldata_close_alter_historicaldata_high_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldata',
            name='date',
            field=models.DateTimeField(db_index=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='ticker',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='historicaldata',
            index=models.Index(fields=['ticker', 'date'], name='algo_tradin_ticker_8ddd30_idx'),
        ),
    ]
