# Generated by Django 4.2.3 on 2024-09-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('message_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('message_text', models.TextField(blank=True, null=True)),
                ('date_sent', models.DateTimeField()),
                ('is_bot', models.BooleanField(default=False)),
                ('chat_type', models.CharField(choices=[('private', 'Private'), ('group', 'Group'), ('supergroup', 'Supergroup'), ('channel', 'Channel')], max_length=50)),
                ('reply_to_message_id', models.BigIntegerField(blank=True, null=True)),
                ('location', models.JSONField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
